//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTeam2_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMembers()
        {
            this.tArticle = new HashSet<tArticle>();
            this.tArticleLove = new HashSet<tArticleLove>();
            this.tComment = new HashSet<tComment>();
            this.tLogIORecord = new HashSet<tLogIORecord>();
            this.tReArticle = new HashSet<tReArticle>();
            this.tReArticleLove = new HashSet<tReArticleLove>();
            this.tReComment = new HashSet<tReComment>();
        }
    
        public int MemberID { get; set; }
        public string fMemberName { get; set; }
        public string fNationality { get; set; }
        public string fAccount { get; set; }
        public string fPassword { get; set; }
        public string fVerificationCode { get; set; }
        public System.DateTime fRegisteredDate { get; set; }
        public string fNickname { get; set; }
        public System.DateTime fBirthday { get; set; }
        public string fGender { get; set; }
        public string fLivingArea { get; set; }
        public string fOccupation { get; set; }
        public string fJLPTLevel { get; set; }
        public string fGoal { get; set; }
        public string fIdentity { get; set; }
        public bool fAlive { get; set; }
        public string ImgURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tArticle> tArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tArticleLove> tArticleLove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLogIORecord> tLogIORecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReArticle> tReArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReArticleLove> tReArticleLove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReComment> tReComment { get; set; }
    }
}
