//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTeam2_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNWord
    {
        public int No { get; set; }
        public string 日文 { get; set; }
        public string 中文 { get; set; }
        public string 假名 { get; set; }
        public string 種類 { get; set; }
        public string 難度 { get; set; }
    }
}
