//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTeam2_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tReArticle()
        {
            this.tReArticleLove = new HashSet<tReArticleLove>();
            this.tReComment = new HashSet<tReComment>();
        }
    
        public int ReArticleID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Main { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public Nullable<int> LoveCount { get; set; }
    
        public virtual tArticle tArticle { get; set; }
        public virtual tMembers tMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReArticleLove> tReArticleLove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReComment> tReComment { get; set; }
    }
}
